### ISSUE TITLE
Propagation unwanted behavior > Titles are automatically filled in wrong locale for other locales

### ISSUE THREAD

**Issue by frontedbe** [verbb/navigation#73]
### Description
When creating and adding items to a navigation which propagates accross all sites / locales, the nav items are correctly added to each locale. Unfortunately the titles are also automatically filled in / propagated across the different locales. Which is non-desirable, I don't want the dutch title filled in for the french and english version, I want it to be empty so the nav item gets his title from the section's title in it's proper locale. I've added a screenshot of what happens => [view screenshot](https://cl.ly/3f885d1b1710)

### Steps to reproduce

1. Create multiple sites with different locale
2. Create navigation that propagates
3. Add entries to the nav and switch locale/site
4. See how titles of nav items in a different locale are automatically filled in with the titles of the previous locale

### Additional info

- Plugin version: 1.1.3
- Craft version: 3.1.14

**Comment by engram-design** [comment]
Should be fixed in [1.1.4](https://github.com/verbb/navigation/releases/tag/1.1.4)

**Comment by frontedbe** [comment]
Thanks for the quick fix @engram-design!
Only thing I notice now is that the sort order of nav items isn't applied correctly across all sites/locales when changing for the primary site

**Comment by engram-design** [comment]
@mdominguez Would you be able to provide an example or more detail? Can't seem to notice any ordering issues on my end...

**Comment by frontedbe** [comment]
Hmm still experiencing this ordering issue, even in an other project.. When propagating nav items, the sort order isn't respected on the other sites than the primary site where you add the nav items... I'll send you a message on Discord with an example if that's alright?

**Comment by frontedbe** [comment]
Pff really struggling here => [view screenshot](https://cl.ly/4ad8b0c27837)

**Comment by engram-design** [comment]
Thanks for the screenshot, although wondering it its possible to see a video? Just interested in how exactly its happening, and under what scenarios...

**Comment by frontedbe** [comment]
Here you go => [view video](https://cl.ly/7061ca9412fc)

**Comment by frontedbe** [comment]
Hi Josh, do you recommend disable'ing the propagation setting for the time being or is there a fix foreseen in the near future? I really want to avoid having to build up this mega menu again we're having on this client's site. As you can tell from the video I provided, it really is a burden atm, thanks for the heads up!

**Comment by engram-design** [comment]
@mdominguez Thanks for the video. I can see you're getting a bunch of errors when first adding nodes , which I've fixed in the latest `craft-3` branch. If you want to give that a go via `composer require verbb/navigation:dev-craft-3`.

With regards to your video (thanks!) I can see you're trying to re-order nodes in one site, but that's not reordering nodes in the other. That's something I'm currently looking into how best to address. The issue is that navigation nodes don't act the same way as say entries do with regards to re-ordering, where you'll notice if you nest or move items, they are reflected across your sites. I'll keep you updated.

**Comment by engram-design** [comment]
@mdominguez Should be all sorted in [1.1.8](https://github.com/verbb/navigation/releases/tag/1.1.8), as I've changed the way nodes are propagated now.
